name: CI of all packages
on:
    pull_request:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: taiga-family/ci/actions/setup/node@1.20.0
              with:
                  node-version: 12.x
            - run: |
                  npm run build
                  npm run lint
                  npm run test
            - uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
