name: CI
on:
  pull_request:
  push:
    branches: [main]

env:
  NX_SKIP_CACHE: true
  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.71.2
      - uses: taiga-family/ci/actions/setup/node@v1.71.2

      - run: |
          if [[ "${{ env.SUPPORT_AUTO_PUSH }}" == "true" ]]; then
              npm run prettier -- --write
              npm run stylelint -- --fix
              npm run lint -- --fix
          else
              npm run prettier -- --check
              npm run stylelint
              npm run lint
          fi

      - run: npx nx build ng-polymorpheus
      - run: npx nx build demo
      - run: npx nx test ng-polymorpheus
      - uses: codecov/codecov-action@v4
      - uses: taiga-family/ci/actions/auto/push@v1.71.2
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true
